name: lab03 workflow docker compose
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package
        working-directory: Labo02CI  # 👈 tell Maven where pom.xml is

      - name: Run docker compose
        run: docker compose up --abort-on-container-exit
        working-directory: Labo02CI  # 👈 tell Docker where docker-compose.yml is
